import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/AppComponents/Header";
import AdminContextProvider from "@/context/admin";
import { ChakraProvider } from "@chakra-ui/react";
import { getSession } from "@/action";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }) {
  const session = await getSession();
  const isAdmin = session.userid;
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <AdminContextProvider>
            <div className="">{!isAdmin ? <Header /> : null}</div>
            <div className={`${isAdmin ? "" : "md:px-12"} py-20`}>
              {children}
            </div>
          </AdminContextProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
