import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/AppComponents/Header";
import { ChakraProvider } from "@chakra-ui/react";
import { getSession } from "@/action";
import Footer from "@/components/AppComponents/Footer";
// import { redirect } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 
export default async function RootLayout({ children }) {
  const session = await getSession();
  const isAdmin = session.userid;
  const isUser = session.email;
  console.log("this is from layout", isUser);
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <div className="">{!isAdmin ? <Header /> : null}</div>
          <div className={`${isAdmin ? "" : "md:px-12"} py-20`}>{children}</div>
          <div className="">{!isAdmin ? <Footer /> : null}</div>
        </ChakraProvider>
      </body>
    </html>
  );
}
